(function(){window.detail=function(){utils.main();}})();if(!Element.prototype.closest){Element.prototype.closest=function(s){var el=this;do{if(Element.prototype.matches.call(el,s))return el;el=el.parentElement||el.parentNode;}while(el!==null&&el.nodeType===1);return null;};}
var utils={main:function(){this.jsDetect();this.imgZoom();this.navSearch();this.lazyHtml();this.liveBlog();},jsDetect:function(){document.getElementsByTagName("html")[0].classList.remove("no-js");},imgZoom:function(){var container=document.querySelector(".story__text");var lightboxID="gd-lightbox";if(container){document.addEventListener("click",function(e){if(e.target&&e.target.matches(".inline-photo img")){var imgSrc=e.target.currentSrc||e.target.src;var lightbox=document.createElement('div');lightbox.id=lightboxID;lightbox.innerHTML='<img src="'+imgSrc+'">';container.appendChild(lightbox);}
if(e.target.matches("#"+lightboxID)||e.target.matches("#"+lightboxID+" img")){var node=document.getElementById(lightboxID);if(node.parentNode){node.parentNode.removeChild(node);}}});}},navSearch:function(){var searchButton=document.getElementById('mainNavSearchButton');var searchForm=document.getElementById('mainNavSearchForm');if(searchButton&&searchForm){searchButton.addEventListener('click',function(){this.classList.toggle('is-visible');searchForm.classList.toggle('is-visible');},false);}},lazyHtml:function(){try{var targets=document.querySelectorAll('.lazy-html');var io=new IntersectionObserver(function(entries,observer){entries.forEach(function(entry){if(entry.intersectionRatio>0){xhrLoader(entry.target);observer.unobserve(entry.target);}});},{rootMargin:"0px 0px 500px 0px"});for(i=0;i<targets.length;i++){io.observe(targets[i]);};xhrLoader=function(id){var t=id;var t_url=t.dataset.src;var xhr=new XMLHttpRequest();xhr.open("GET",t_url);xhr.onreadystatechange=function(e){if(xhr.readyState==4&&xhr.status==200){t.innerHTML=xhr.responseText;t.classList.remove('lazy-html');var allScripts=t.getElementsByTagName('script');for(var n=0;n<allScripts.length;n++){eval(allScripts[n].innerHTML);if(allScripts[n].src!=null){var script=document.createElement("script");script.src=allScripts[n].src;document.body.appendChild(script);}}
t.removeAttribute('style');}
if(xhr.readyState==4&&xhr.status==404){console.error("Errore: ",xhr.statusText);}};xhr.send();}}catch(e){}},liveBlog:function(){var trigger=document.getElementById("liveblogIndexTrigger");if(trigger){toggler("#liveblogIndexTrigger",".liveblog__index","is-open")}}}
var toggler=function(trigger,panel,activeClass){try{var trigger=document.querySelector(trigger);var panel=document.querySelector(panel);trigger.addEventListener("click",function(){panel.classList.toggle(activeClass);})}catch(error){}}
var commentsToggler=function(){var pageHtml=document.getElementsByTagName("HTML")[0];var activeClass='is-comment-panel-open';if(window.location.hash=="#commenta"){pageHtml.classList.add(activeClass);}
document.addEventListener("click",function(e){if(e.target){if(e.target.matches("#commentsTrigger")||e.target.matches("#commentsCloseTrigger")){pageHtml.classList.toggle(activeClass);}
if(e.target.closest(".story__comments"))return
else if(!e.target.matches("#commentsTrigger"))pageHtml.classList.remove(activeClass);}});};
;window.kwait=window.kwait||[];kwait.push(['call',"detail_js"]);